spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/iot_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

mqtt:
  broker: tcp://srv38.mikr.us:40131
  client-id: server-backend-app
  username: iotproject
  password: iotproject
  topics:
    command: lamps/+/command
    metrics: lamps/+/metrics

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970